### ISSUE TITLE
Name request 🙏

### ISSUE THREAD

**Issue by ZachNagengast** [Mwni/diffusionkit#2]
Hi @Mwni, I'm reaching out to see if you'd be open to the use of the name "diffusionkit" in pypi for this repo https://www.github.com/argmaxinc/DiffusionKit. If you'd like to join as a contributor, we'd also be happy to have your help, as I see you've made some good progress with this project. We are planning to make it an active and central location for Core ML and Python + MLX inference for SD3 and various other models, and I think `diffusionkit` would be a great name for the package to help the community disambiguate between these projects. If you're open to it, we'd be super grateful 🙏.

**Comment by endomorphosis** [comment]
Mwni rght now has cancer, but i will try to get in touch with him.

**Comment by endomorphosis** [comment]
I just got out of a meeting with Christoph of LAION, can you send me your discord handle?

**Comment by ZachNagengast** [comment]
Oh wow very sorry to hear that, best wishes from us and thank you for the response.

I'm `zachnagengast` on discord

**Comment by Mwni** [comment]
It appears I'm not able to transfer it, I can delete it so the name is supposedly reclaimable. I will take no responsibility however.

![image](https://github.com/Mwni/diffusionkit/assets/13929820/71ad0b2c-318a-4c32-b0eb-90a8c48b819c)

**Comment by ZachNagengast** [comment]
Understood, thanks for checking. If you are able to make it reclaimable, then it will be safe for that short timespan since there is unlikely to be another project with that name.

**Comment by Mwni** [comment]
Alright, it's deleted. Good luck.

**Comment by ZachNagengast** [comment]
Thank you @Mwni looks like it worked. You're amazing for handling this all things considered, we owe you one 🍻 🙏
